import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";

import "./globals.css";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(recursive.className)}>
                <Navbar />

                <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)] grainy-light">
                    <div className="flex flex-1 flex-col h-full">
                        <Providers>
                            {children}
                        </Providers>
                    </div>

                    <Footer />
                </main>

                <Toaster />
            </body>
        </html>
    );
}
